'use client';
import { useMemo, useState } from 'react';
import { buildMapRespawnRecords, getRespawnPhase, phaseLabel, respawnMaps, type RespawnKind, type RespawnRecord } from '../../src/respawn-timers';
import type { MapHuntingSnapshot } from '../../src/map-hunting';
import { AppShell, Icon } from '../app-shell';
type Filter = 'all' | RespawnKind | 'active';
const filters: ReadonlyArray<{ id: Filter; label: string }> = [{ id: 'all', label: 'Wszystkie' }, { id: 'boss', label: 'Bossy' }, { id: 'metin', label: 'Metiny' }, { id: 'active', label: 'Okno / na mapie' }];
function formatWindow(record: RespawnRecord) { return record.entity.respawnTimeMin === record.entity.respawnTimeMax ? `${record.entity.respawnTimeMin} min` : `${record.entity.respawnTimeMin}–${record.entity.respawnTimeMax} min`; }
export function MapHunting({ initialSnapshot }: { initialSnapshot: MapHuntingSnapshot }) {
 const [mapKey, setMapKey] = useState(respawnMaps[0]?.key ?? ''); const map = respawnMaps.find((candidate) => candidate.key === mapKey) ?? respawnMaps[0]; const [channel, setChannel] = useState(1); const [filter, setFilter] = useState<Filter>('all'); const [records, setRecords] = useState<readonly RespawnRecord[]>(() => map ? buildMapRespawnRecords(map, 1) : []); const [notice, setNotice] = useState(''); const now = Date.now();
 const visible = useMemo(() => records.filter((record) => { const phase = getRespawnPhase(record, now); return filter === 'all' || record.kind === filter || (filter === 'active' && (phase === 'window' || phase === 'on_map' || phase === 'approaching')); }), [records, filter, now]);
 const changeMap = (nextKey: string) => { const next = respawnMaps.find((candidate) => candidate.key === nextKey); if (!next) return; setMapKey(nextKey); setChannel(1); setRecords(buildMapRespawnRecords(next, 1)); }; const changeChannel = (next: number) => { if (!map) return; setChannel(next); setRecords(buildMapRespawnRecords(map, next)); }; const markKilled = (key: string) => { setRecords((current) => current.map((record) => record.key === key ? { ...record, confirmedAt: Date.now(), confirmedBy: initialSnapshot.viewerName } : record)); setNotice('Zapisano zbicie w tym widoku. Po podłączeniu API ten rekord trafi do bota i dziennika zmian.'); };
 return <AppShell activeSection="maps" viewerName={initialSnapshot.viewerName}><main className="respawn-page" id="main-content"><header className="respawn-header"><div><span className="eyebrow">Wyprawa</span><h1>Metiny i bossy</h1><p>Osobny moduł respawnów. Nie jest połączony z EQ, księgami ani timerami postaci.</p></div><div className="respawn-header-note"><Icon name="clock" size={19}/><span>Ręczne potwierdzenie → wspólny timer</span></div></header><section className="respawn-layout"><aside className="panel respawn-map-panel"><header><span className="section-kicker">Mapa</span><h2>Wybierz teren</h2></header><div className="respawn-map-list">{respawnMaps.map((candidate) => <button className={candidate.key === map?.key ? 'is-active' : ''} key={candidate.key} onClick={() => changeMap(candidate.key)} type="button"><span style={{ background: candidate.color ?? '#657187' }}/><strong>{candidate.key}</strong><small>{candidate.bosses.length + candidate.metins.length} timerów</small></button>)}</div></aside><section className="panel respawn-list-panel"><header className="respawn-list-header"><div><span className="section-kicker">{map?.key} · kanał {channel}</span><h2>Timery respawnu</h2></div><div className="respawn-channels">{Array.from({ length: map?.channels ?? 0 }, (_, index) => index + 1).map((value) => <button aria-pressed={value === channel} className={value === channel ? 'is-active' : ''} key={value} onClick={() => changeChannel(value)} type="button">CH{value}</button>)}</div></header><div className="respawn-filters">{filters.map((item) => <button aria-pressed={filter === item.id} className={filter === item.id ? 'is-active' : ''} key={item.id} onClick={() => setFilter(item.id)} type="button">{item.label}</button>)}</div><div className="respawn-records">{visible.map((record) => { const phase = getRespawnPhase(record, now); return <article className={`respawn-record is-${phase}`} key={record.key}><span className="respawn-record-icon"><Icon name={record.kind === 'boss' ? 'activity' : 'map'} size={17}/></span><div className="respawn-record-copy"><strong>{record.entity.name}</strong><span>{record.kind === 'boss' ? 'Boss' : 'Metin'} · respawn {formatWindow(record)} · {record.confirmedBy ? `zbił ${record.confirmedBy}` : 'brak potwierdzenia'}</span></div><span className="respawn-phase">{phaseLabel(phase)}</span><button onClick={() => markKilled(record.key)} type="button">{record.confirmedAt ? 'Zbite ponownie' : 'Oznacz zbite'}</button></article>; })}{visible.length === 0 && <p className="respawn-empty">Brak timerów w tym filtrze.</p>}</div></section></section><p aria-live="polite" className="sr-only">{notice}</p><div className="mock-notice">Katalog i reguły pochodzą z poprzedniej aplikacji. Trwały zapis, prawa oraz powiadomienia Discord zostaną dodane razem z API — nie jako atrapowe przełączniki.</div></main></AppShell>;
}
