export const PLAYER_WORKSPACE_CONFIG = Symbol('PLAYER_WORKSPACE_CONFIG');
export const PLAYER_WORKSPACE_POOL = Symbol('PLAYER_WORKSPACE_POOL');
export const PLAYER_WORKSPACE_REPOSITORY = Symbol('PLAYER_WORKSPACE_REPOSITORY');
export const CHARACTER_OWNERSHIP_PORT = Symbol('CHARACTER_OWNERSHIP_PORT');
export const INBOUND_CLIENT_REGISTRY = Symbol('INBOUND_CLIENT_REGISTRY');
export const ASSERTION_JTI_STORE = Symbol('ASSERTION_JTI_STORE');
