// AUTO-GENERATED by tools/scripts/migration-inventory.mjs — do not edit manually.
export const schemaMigrationManifest = {
  service: 'activity',
  trackingTable: 'activity_schema_migrations',
  count: 19,
  foundationId: '001_activity_foundation.sql',
  latestId: '019_performance_indexes.sql',
} as const;
