// AUTO-GENERATED by tools/scripts/migration-inventory.mjs — do not edit manually.
export const schemaMigrationManifest = {
  service: 'activity',
  trackingTable: 'activity_schema_migrations',
  count: 18,
  foundationId: '001_activity_foundation.sql',
  latestId: '018_lfg_audit_suppressions.sql',
} as const;
