// AUTO-GENERATED by tools/scripts/migration-inventory.mjs — do not edit manually.
export const schemaMigrationManifest = {
  service: 'identity',
  trackingTable: 'identity_schema_migrations',
  count: 2,
  foundationId: '001_better_auth.sql',
  latestId: '002_player_profile_foundation.sql',
} as const;
