// AUTO-GENERATED by tools/scripts/migration-inventory.mjs — do not edit manually.
export const schemaMigrationManifest = {
  service: 'identity',
  trackingTable: 'identity_schema_migrations',
  count: 3,
  foundationId: '001_better_auth.sql',
  latestId: '003_player_game_accounts.sql',
} as const;
