export const AUTHORIZATION_CONFIG = Symbol('AUTHORIZATION_CONFIG');
export const AUTHORIZATION_POOL = Symbol('AUTHORIZATION_POOL');
export const AUTHORIZATION_STORE_PORT = Symbol('AUTHORIZATION_STORE_PORT');
export const SESSION_REVOKE_PORT = Symbol('SESSION_REVOKE_PORT');
export const INBOUND_CLIENT_REGISTRY = Symbol('INBOUND_CLIENT_REGISTRY');
export const ASSERTION_JTI_STORE = Symbol('ASSERTION_JTI_STORE');
