// AUTO-GENERATED by tools/scripts/migration-inventory.mjs — do not edit manually.
export const schemaMigrationManifest = {
  service: 'authorization',
  trackingTable: 'authorization_schema_migrations',
  count: 5,
  foundationId: '001_authorization_foundation.sql',
  latestId: '005_activity_permission_catalog.sql',
} as const;
