export const DISCORD_GATEWAY_TOKEN = Symbol('DISCORD_GATEWAY_TOKEN');
export const DISCORD_CONFIG_TOKEN = Symbol('DISCORD_CONFIG_TOKEN');
export const DISCORD_ACTIVITY_CLIENT_TOKEN = Symbol('DISCORD_ACTIVITY_CLIENT_TOKEN');
