export const DISCORD_GATEWAY_TOKEN = Symbol('DISCORD_GATEWAY_TOKEN');
export const DISCORD_CONFIG_TOKEN = Symbol('DISCORD_CONFIG_TOKEN');
export const TECHNIKA_CONFIG_STORE_TOKEN = Symbol('TECHNIKA_CONFIG_STORE_TOKEN');

export const MEMBER_ACTIVITY_STORE_TOKEN = Symbol('MEMBER_ACTIVITY_STORE_TOKEN');
export const MEMBER_ACTIVITY_COLLECTOR_TOKEN = Symbol('MEMBER_ACTIVITY_COLLECTOR_TOKEN');
