export const DISCORD_GATEWAY_TOKEN = Symbol('DISCORD_GATEWAY_TOKEN');
export const DISCORD_CONFIG_TOKEN = Symbol('DISCORD_CONFIG_TOKEN');
export const TECHNIKA_CONFIG_STORE_TOKEN = Symbol('TECHNIKA_CONFIG_STORE_TOKEN');
